# **O Básico sobre Tensores**

In [1]:
import torch

In [4]:
# Number
tensor1 = torch.tensor(4.)
tensor1

tensor(4.)

In [6]:
tensor1.dtype

torch.float32

In [7]:
# Vector
tensor2 = torch.tensor([1.,2,3,4])
tensor2

tensor([1., 2., 3., 4.])

In [8]:
tensor2.dtype

torch.float32

In [11]:
# Matrix
tensor3 = torch.tensor([[5.,6],
                       [7,8],
                       [9, 10]])
tensor3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [28]:
# 3-dimensional array
tensor4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
tensor4.dtype

torch.float32

In [13]:
print(tensor1)
tensor1.shape

tensor(4.)


torch.Size([])

In [16]:
print(tensor2)
tensor2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [17]:
print(tensor3)
tensor3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [25]:
print(tensor4)
tensor4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [30]:
# 3-dimensional array
''' tensor5 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19, 20]]])
tensor5 '''

' tensor5 = torch.tensor([\n    [[11, 12, 13],\n     [13, 14, 15]],\n    [[15, 16, 17],\n     [17, 18, 19, 20]]])\ntensor5 '

> Não é possível criar um tensor com dimensões irregulares pois cada dimensão deve ter o mesmo comprimento em  todas as suas subdimensões.

> Para tarefas de *Deep Learning* é importante criar tensores com valores do tipo float.

In [43]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

> O parâmetro requires_grad é utilizado para indicar se um tensor deve ser rastreado para cálculos de gradientes, isso é crucial para a execução de backpropagation em redes neurais.

In [40]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [41]:
y.backward()

In [42]:
print('dy/dx', x.grad) # w
print('dy/dw', w.grad) # x
print('dy/db', b.grad) # 1

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


> O “grad” em w.grad significa gradiente, que é outro termo para derivada, usado principalmente ao lidar com matrizes.

# **Funções com Tensores**

In [52]:
tensor6 = torch.full((3,2), 42, dtype=torch.float32)
tensor6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [53]:
tensor3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [56]:
tensor7 = torch.cat((tensor3, tensor6))
tensor7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [57]:
# Calcula o seno de cada elemento
tensor8 = torch.sin(tensor7)
tensor8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [58]:
tensor8.shape

torch.Size([6, 2])

In [60]:
tensor9 = tensor8.reshape(3,2,2)

> Note que as dimensões devem possuir o mesmo valor quando multiplicadas, isto é:
* 6 * 2 = 12
* 3 * 2 * 2 = 12

# **Interoperabilidade entre PyTorch e NumPy**

In [63]:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

> É possível converter um array NumPy para um tensor PyTorch

In [64]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [65]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [67]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])